# Generated by Django 2.2.5 on 2019-09-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakTimeCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.CharField(max_length=200)),
                ('todayDate', models.DateField()),
                ('breakStartTime', models.TimeField()),
                ('breakEndTime', models.TimeField()),
                ('totalBreakTime', models.CharField(max_length=300)),
                ('breakStatus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.CharField(max_length=200)),
                ('currentState', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimeCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.CharField(max_length=200)),
                ('todayDate', models.DateField()),
                ('workStartTime', models.TimeField()),
                ('workEndTime', models.TimeField()),
                ('totalWorkTime', models.CharField(max_length=300)),
                ('workStatus', models.IntegerField(default=0)),
            ],
        ),
    ]
